language: python
dist: trusty
sudo: true
warnings_are_errors: false
python:
- '3.6'
git:
  quiet: true
  depth: 5
branches:
  only:
  - master
  - submitted-data
  - processed-data
install:
- ".travis/install_cimr.sh"
script:
- git lfs pull
- python3 .travis/process_submitted_data.py
after_success:
- ".travis/push_processed_data.sh"
env:
  global:
  - secure: dJGUDZGyS1O4BByPYWXaElHI7siXoYubguremr1+HChbhk59yID/SI8yZEW4BHmakNwOGDRwBgStUNujCIgcNtAWSv5mJLrYpqIc16oMiCV6FJXe71+11edLlEMozAMLN1GyjZ+ou6XttrrD2Fb9nIFnn/g/lj9L6JKd1/o/ragjk/ho1a/oTSTzACXdwAvC/BYTOwPRjQoUzZW/0M1+syv/bcz133h8dqOjXc2UrpDyImNrKiHZfURtILnMN2rEloyXcRs6LUexRtA6FGr8kdCp7kVeVmmw+PuzzWIveNOPVnf8Jiel2wIEJ0G5vw1UyuSUTKX5E2WMnoyNlsIcRWXa97sGhVYk/8GRZEQLuQ86uqHKCq1s6uCU5CbTm55+tMzbe4wCcmEoNtLNdD2cJ3f05Kiiz/lRLXUB6wlY1WZUVtzfSWFBc6vWb1eyPkheQQRRUgGHd8mKVmsG/GJTBN4jzxPEBih+IRiFiaLVNrYLwBQd7iXGIbYPTCB5PZwiFfPzVIc4py2gzq0K3hbNDcSvKH+ex9Cu8IQMch9u/2NLvjaikiltLOSC1T6HI+obsX+LanJx3x40O9uKl4/J68c4paHAxTPtMjmrB5XsTWPE2IzGy4864r2JV8neqgdx7HBcGbrtoiy7F772CmquTGEPaI7y/svdhXfirdlXzRE=
  - secure: XWBCI6NBrOW5gDvnq1FX3Ay5iqNpzf4CWvaotHKKTUky0t3oOtM67sQ7UY9Xig16cWnidjSp8LR12iJ9G7DfSEWeMfj3swphx0rM2wKLaxlahYV82I8YjZGFkL0O0pqG/GvXB1vlIV7dLD8hgeJq5q8qX8hip/qhKSZDY4H/kBX5RGyyag6bb7wjwdGitMoW2F6jXENmRFf7gIMKNztCfRgzmeHZ6A0iD9SfLcsIrvUc4pQCDdZlZcVeYbEJqPOkB7P/pIsUXS6o5iR0vrJnVINFhqIAoaMFwbr76LBkjTnCmJCPh3uBhLic1d6GCG/QdPA/YWkdwy17MEgciflrY941iqjEoxoCnvW6gNxUlVK2+jtC0M49zVd59GZ4N1f3kkSoiTW4TiBJJIAGP/j4mJa0oAS2fVQrw8tUjKSbqyAqqBw/XK2yWUGWkb6fWFq+WxqQMLzzRZMtRDWSHIjD1oxry8sA2sVqNDb7steZicrO1dgODFnZm/rmAq7OW+iY/V+FAO+8OrT8v0KhVi+Ow1Uihm1YWz7VVgjCXW/KGeappRX2ldMQuNZtktQ2lYovL5Pqh77wIPbznxhlxK3/jfJJ4ysvk0hd0DW5bl5ZwJj14uAJ6x7+XhuaBiF2AxM7Hu1/Y81G+Jlsgu/JERY+i6sl9t47ogLXorZwefWvcnQ=
