language: python
dist: trusty
sudo: true
warnings_are_errors: false
python:
- '3.6'
git:
  quiet: true
  depth: 5
branches:
  only:
  - master
  - submitted-data
  - processed-data
install:
- ".travis/install_cimr.sh"
script:
- git lfs pull
- python3 .travis/process_submitted_data.py
deploy:
  provider: releases
  api_key:
    secure: G9xoY49/awLmKt5MKxKR5XZbgHY1P4/yjPnKyek3RO63Y1Oabckv+3ib+6t5TAqXbr7MCZkp/xfUC2reKSIFDcwk7FFcrs4TM5StVojZQx4y/RvStyfSg4kXLxtdYr5Y9ZnmmCbCqhjP0Jkfjo+fk4sPWhe+DgKcDWgiKCjulME5hIwsrEvDcoC/AL5ib30bPpYhOSzecdkaj1ni2nVmdMOaFCLA4aKVwpLPmwZsJWBUk8O7GWXzASD4pe1NcCcEwHnw3VMbQTItK8Nz+LSbnD0kLl0Q21P61H0kOMAgCOpJ63hIKXQvXzJUo7957I9eAikos2fNxV8cXIYz6yp8UXWS/E9k0Z1gCR3se6RMDhrAx469XV9uc7xhDn8Eoa5iu0mc52wdYq2D69yIvKoT/pttIHyRL34hJyVPE8pZ1cXqZQ259kuml1tNM7jQ4ojfSaTofLL5grxrdxjOii2vdlIbBTrSwjOu1KSPaq9LaDRx9Kez9uPNX+h/sWY406Ll0+duu8QCPbmA3eGi7PLoRm8pOBRVpG2CROwQoUEFELoyDz7qjc95UL+Ax8rp5hrWCPIiMq8uJe74Z/Dci56SQQYyFximb3wwrE/2Jv+t759vWbPEAFeCi/n57SDZjNy4/vh9oKKTzA1GxhRnH636bxGVpjtUkXSqQZnI1eHRItc=
  file: 'processed-data/*/*'
  skip_cleanup: true
  on:
    repo: greenelab/cimr-d
