language: python
dist: trusty
sudo: true
warnings_are_errors: false
python:
- '3.6'
git:
  quiet: true
  depth: 5
branches:
  only:
  - master
  - submitted-data
  - processed-data
install:
- ".travis/install_cimr.sh"
script:
- git lfs pull
- python3 .travis/process_submitted_data.py
after_success:
- ".travis/push_processed_data.sh"
env:
  global:
  - secure: knDQSdkbBNnFX6b7S417Yf2Yjx5TM62eb84Te/Z1AFfc+RyIjKNxlOST+ZEAiiyf4dslG4t/EBPJlS4cybZrmx4bn8U3A2H0RmeUlB+o4OOWjd+0DS2aXWNBtIso2NviFkAUERIXSwxPfTh4UQrIU29as+H/vzgKOEdO3qK9UwFY4Qs6AIYuDV5LC1a0dG57lx/+5JJWgWL3DM66DguKkk7dOM5PsM3bCP7Q7Dv+RvimdhV10wWWKwaN4cXgUvbJER0pAO3U1VMthMA4jku4K8IkVHLqNxbPm9/J/dC5LY6g2rsuGNUMDotISgSAePCL99rrewefes72FOvm9E2StUHw62DlIBdW1ld8PzU8OE2dR6jEANKukhc1BPKgr+Se2yZK5Qinnj5TQbZWpyR07Y4txG3QDVSLqh7wJ8dwRbJVou7jKFZXJWuvFoggJpXvCb2WG82OyB2pcQ1EqEJTJkBxhXvOngv9k+FoCy/XPY8bwLWmieiptCe19FhQarObuz1nZWSn6y6eHmVHF2Qf8K77YsL0mbsbxeaZeSFVKGxjtipaOudg/Dt3Pt5B8wN3NQz29ozZkzbSui6U4kIRoqtyQbK1S5pEfW6NWGeGW8RydQBOJkNhlTYPYwIQcyapaviI6Qn0wjN8e+zt22ewY9P9Budad4jPSKdA4DGbuq8=
  - secure: tAj4dQFDP58fTNhFwsByguvachJyMjYub5FqPVACWujt5QTDuLMhg+qkBC6UezHghQ4rtQlzTFK0W6Tzg8upClQ/b+w31HrnSoKpO9V7ESbdJZcfpg+CcKu7UuvIfRryzTJd9RjzuQskGFWetxVncRBNiAAkWDXiQv0mQVSstR2/kzkAQz5f3A0Sy0Lg6UwY5q8t8Aw9OKuxvbeqGdV/uTNfQIWjwzeUKu0PViGsIZSaOWaKD/8BFh170a9eY/sXJKVfOi7sN5BIyH0fCiTT7EV1ANNCd7t03PXXCa4sDexeY8kAbxC/JywsQjdeJ1vg0kh4/15JFYF6aGcJs0ya4DnziaVaxtdrXOPQq69O/Cx5mUYPYHlmMJ0VfVdYM23nPgGK1Y7jD0MxnTInMJ6w0hI1Wdf9PZ+2AfAXEWW4rSMmHwCSaNnSU2MQoPnOF7xOuBZyjrL6dBJLQlu8lMa5sg/Ypgg1oOId/dpHmNX64/yZ5f8qo0U4kXSU0/IvxOxGHkEHJdBgeSz2mWjPMDnem1G6QxO+IIRVGHPsGN3EWMfDDBGkgwnIt393Scqrl+acafo8x2BEIGiLjm+zmZXFRTAGj90aHYdXPl2VXITrPQjyOztDnL5adcyGk9rd8JRsH4cjYz6WS8KwMssHCDnQL85ynbWq8/SATYKVe9nK9W4=

